### ISSUE TITLE
Porting interactive functionality to Symfony

### ISSUE THREAD

**Issue by wouterj** [laravel/prompts#17]
I asked about this on [Twitter last week](https://twitter.com/wouterjnl/status/1681991895998689282), but I realize that is not the best place to discuss this. I'm really digging the interactive prompts (arrow-based choice lists & completion dropdowns) of this library! This is something I was trying to introduce to Symfony Console for many years (but lacking the stty skills needed for this).

Would it be an idea to see if this part of Prompts can be ported back to Symfony Console, a library you already depend on in the Laravel ecosystem and this library? That way, a larger part of the PHP ecosystem can have this much better terminal UX (including tooling used in the Laravel ecosystem like Composer and PHPstan).

The way I see it, this functionality is a perfect fit for the [Question classes in Symfony Console](https://github.com/symfony/console/tree/6.3/Question). Laravel Prompts can then use the question classes, and add the custom "Laravel style" (plus any other extra integration, like the helper functions) on top of it.

Of course, given the code in this library is MIT, I can always try this proposal without your consent. But I'm looking forward to hear your ideas about this (e.g. did you try this and reached a major blocker already, is this just "not worth it" for your time, are you happy to try this out, or can I stalk a bit when experimenting with this myself :grin: )

**Comment by jessarcher** [comment]
Hey @wouterj! Sorry I missed your Twitter post - thank you for sharing it!

I would love to see something like this in Symfony. The challenge is supporting native Windows (i.e. `php.exe` without WSL) and potentially other environments. Currently, we're configuring the Prompts in Laravel to [fall back to Symfony in Windows](https://github.com/laravel/framework/pull/46772/files#diff-9c0b99959f28e3b7a54a93a4ff67818de374a378726f8ecd16fa3c3bded6a9c7R27) because I couldn't find a way to make the arrow keys work, amongst other things.

I've briefly explained the challenges I faced with Windows at https://github.com/laravel/docs/pull/8924#issuecomment-1654762739.

In Symfony, it's already possible to use the arrow keys as an alternative mode for selection. However, as the entries can still be typed manually, it's still useable with the arrow or tab keys (albeit more frustratingly). After trying to implement Laravel Prompts in Windows, I gained a new understanding and appreciation for why Symfony's prompts are the way they are. It appears they have made an admirable decision to sacrifice some usability in exchange for supporting more environments.

Unless we can figure out how to solve the problems mentioned in my linked comment, I think the only alternative would be exploring alternative UI approaches that allow for graceful degradation.

For what it's worth, this library was designed to work with any PHP project, not just Laravel. However, the Symfony fallback implementation is only configured out of the box when used with Laravel, as originally this package did not have any Symfony dependencies. We added Symfony Console as a dependency towards the end when we needed a shared output buffer to know how many newlines to output before and after each prompt when interleaved with other console output in Laravel.

It's also worth noting that the Node packages that inspired me seem to have similar problems in native Windows, as does ReactPHP's stdio package:

* https://github.com/natemoo-re/clack/tree/main/packages/prompts (this one was unusable on Windows)
* https://github.com/terkelg/prompts (I think this one was somewhat usable due to its UI)
* https://github.com/clue/reactphp-stdio#install

**Comment by driesvints** [comment]
Hey @wouterj. Was the fact that you could already use the package in Symfony projects enough or are you looking for some other (deeper) integration? Please let us know what more thought you have here 🙂

**Comment by ppastercik** [comment]
Hi, @jessarcher.

I don't know where to put this. But after seeing this issue, I took a close look at laravel/prompts. I work on Windows and it irritates me that the console use of PHP on the Windows system is limited, so I like the idea that it could work on Windows (even without WSL). I've tried some things like updating PHP source codes, and **it works**! See below for more detailed information.

You are correct that PHP on native Windows by default has no useful way to implement the correct behavior (reading arrow keys, etc). So I thought I'd rewrite some PHP source codes. I gave it a shot even though the last time I did C/C++ was many years ago at school. So after locally updating some PHP source code (8.2.9) and building it, then updating the laravel/prompts code to use the newly implemented PHP features, and it works. It works on CMD, Git Bash and PowerShell command lines (I haven't tried other Windows command lines yet). But as I wrote, if it's going to work, the PHP source code has to be updated, and I don't know if the PHP developers would agree to the necessary code update. But this is just a functionality extension, so it could work, just define the right way to implement these features.

For a better description of what the problems were, I list them here along with the possible solutions I came up with:
- The ability to not to echo the entered characters
	- Now this is not possible in PHP on Windows.
	- But by modifying the PHP source code it is possible to add this option. It is possible by calling the `SetConsoleMode` function, which will clear the `ENABLE_ECHO_INPUT` flag (it is set by default).
		- Therefore, I added a custom function to PHP to set/unset it for a specific console input stream.
- The ability to read every key, not just the line after `Enter`
	- Now this is not possible in PHP on Windows.
	- But by modifying the PHP source code it is possible to add this option. It is possible by calling the `SetConsoleMode` function, which will clear the `ENABLE_LINE_INPUT` flag (it is set by default).
		- Therefore, I added a custom function to PHP to set/unset it for a specific console input stream.
- The ability to read special keys, i.e. arrow keys and even special keys like `Backspace` etc.
	- Now this is not possible in PHP on Windows.
	- But by modifying the PHP source code it is possible to add this option. It is possible by calling the `SetConsoleMode` function, which sets the `ENABLE_VIRTUAL_TERMINAL_INPUT` flag (it is unset by default).
		- Therefore, I added a custom function to PHP to set/unset it for a specific console input stream.
- The ability to read `Ctrl+C` and not process it
	- Now this is not possible in PHP on Windows.
	- But by modifying the PHP source code it is possible to add this option. It is possible by calling the `SetConsoleMode` function, which will clear the `ENABLE_PROCESSED_INPUT` flag (it is set by default).
		- Therefore, I added a custom function to PHP to set/unset it for a specific console input stream.
- Working with multiple command line types in Windows
	- CMD command line
		- The input is a standard console stream, so I can use the functions added to PHP mentioned above.
	- PowerShell command line
		- The input is a standard console stream, so I can use the functions added to PHP mentioned above.
	- Git Bash command line (differs in how it is called)
		- Called with `php artisan app:prompt`
			- Input is a standard console stream, so I can use the functions added to PHP mentioned above.
		- Called with `php.exe artisan app:prompt`
			- The input is a pipe stream, so the functions mentioned above are unusable, but in this case I can use `stty` because `Git bash` has its own implementation of `stty`. However, I think this implementation also uses `SetConsoleMode` to set the console behavior, because when I tested my PHP functions to set the console behavior and then call `stty`, my settings were overwritten, so only one approach must be used. So it has to check if the input is console or pipe stream.
- Returned character for `Enter` key
	- On Linux it's the `\n` character.
	- On Windows it's the `\r` character, so I had to update `laravel/prompts` to handle both characters to submit values.

This would have to be properly tested for other command lines on the Windows platform to work. Furthermore, a suitable implementation of adding the functionality to PHP would also have to be resolved, because now it's only a proof of concept. And there is the question of whether to somehow merge it for Windows and Linux (wire up stty or something), or just add functionality for Windows.

Extending PHP to include the functionality may then take some time, if the PHP developers agree to it, and it is possible that even then it would only be from a new version of PHP.

So I'd like to ask about your opinion if it's worth implementing, or is it a waste of time?

Alternatively, do you have any insights on this? Or are there other things for Windows that are necessary for this, but I missed it?

PS:
I mistakenly thought it was necessary to add a non-blocking read of the console input, so the info below is not related to this issue, but it is interesting.

It's not possible in PHP on Windows now. But by updating PHP source code I managed to implement a workaround for non-blocking reading of console input in the PHP on the Windows platform. I use the `PeekConsoleInput` function to see if any character input exists, so we can safely use the `read` function without blocking. However, there is a problem with some keys when using console line input. For example, the `F4` key, which brings up some modal window in CMD that I didn't know about and discovered it now. So for this to work 100%, it needs more work.

**Comment by jessarcher** [comment]
Hi @ppastercik,

Wow! Well done! This sounds very promising and exciting, and I think it's worth implementing.

It could be hard to get it into PHP, though. But I think we could make a convincing argument for it, given the current limitations.

Failing that, It sounds like this could be included in a PHP extension, but that isn't the greatest developer experience.

Alternatively, I wonder whether we could achieve this with the [FFI extension](https://www.php.net/manual/en/intro.ffi.php), which might be a bit less annoying to install than a third-party extension.

**Comment by ppastercik** [comment]
Now I tried the same procedure as with `stty`, i.e. for example calling a special program that would set the console behavior. But when the program finishes, the console behaviour regarding `echo` and `CTRL+C` reverts to normal behaviour, but the arrow (and other special characters) settings persist, so it's useless unless all settings are preserved :(. But it's strange that something is preserved.

So the preferred way is to add this to core PHP if you can, otherwise as a PHP extension. Or an FFI extension as you suggest, but I don't know much about that. I've looked at the documentation, but haven't studied it in depth, so I don't know yet if it's possible to use PHP's internal structures, which would help. But I can give it a try if it doesn't work otherwise.

I tried searching about this issue on their bug tracker (https://bugs.php.net/) and github issues (https://github.com/php/php-src/issues), but I didn't find anything relevant. @jessarcher do you know of anything relevant where I should post my suggestion? Or should I start a new issue with this suggestion (I don't want to make a duplicate issue if there is one, so I'd rather ask if you know of anything)?

**Comment by jessarcher** [comment]
> Now I tried the same procedure as with `stty`, i.e. for example calling a special program that would set the console behavior. But when the program finishes, the console behaviour regarding `echo` and `CTRL+C` reverts to normal behaviour, but the arrow (and other special characters) settings persist, so it's useless unless all settings are preserved :(. But it's strange that something is preserved.

Interesting idea! There is a precedent for this in Symfony too. On Windows, it calls a bundled `hiddeninput.exe` file to handle hidden input (i.e. password inputs).

https://github.com/symfony/console/blob/baad2fac42f37fef925482313291044143d3e00b/Helper/QuestionHelper.php#L417

With the `stty` implementation we need to manually restore the console behaviour afterwards - was that not possible with your approach?

https://github.com/laravel/prompts/blob/a109cc55fb9af365a06aff236184173e673785bc/src/Prompt.php#L83-L86

**Comment by jessarcher** [comment]
Thanks for the clarification, @ppastercik.

I've read through the [`SetConsoleMode` docs](https://learn.microsoft.com/en-us/windows/console/setconsolemode) you posted, and it seems very strange that some settings persist and others don't, given they all operate on a console input buffer. I'd expect it to be all or nothing!

How are you determining which input handle to pass to the `hConsoleHandle` parameter? Is it possible it's not the same as `STDIN` in PHP?

In any case, support in PHP would be ideal. With your proposed changes, Windows support would be better than Linux and macOS, where `stty` is required.

To clarify my understanding, these are the flags we need to toggle, their default, and their purpose:

| Mode                            | Operates on | Default  | Purpose                                                         |
|---------------------------------|-------------|----------|-----------------------------------------------------------------|
| `ENABLE_ECHO_INPUT`             | Input       | Enabled  | Writes input to the screen buffer                               |
| `ENABLE_LINE_INPUT`             | Input       | Enabled  | Waits for carriage return                                       |
| `ENABLE_VIRTUAL_TERMINAL_INPUT` | Input       | Disabled | Converts input into sequences (for arrow keys, backspace, etc.) |
| `ENABLE_PROCESSED_INPUT`        | Input       | Enabled  | System processes Ctrl+C instead of input buffer                 |

I don't have any preference for the PHP API. Exposing all console mode flags seems ideal, but perhaps there are good reasons not to.

I'm not sure who at PHP is responsible for this, but I think a good next step would be to talk to whoever that is so that we can figure out what would have the best chance of a successful RFC.

**Comment by ppastercik** [comment]
Great job @andyduke. I tried it and it worked. But I found some bugs that I hope can be fixed. For example, pasting text from the clipboard doesn't work (not process each character pasted from clipboard). I'll write up the bugs in your package issues.

Your solution confirms that although my solution will not be implemented in PHP itself, we have a solution, but with a dependency on the FFI extension.

However, I prefer to implement it in PHP itself without dependency on the FFI extension, so that users can use the interactive console in Windows without having to enable the FFI extension.

Today, I finally finished testing my solution on different types of command lines in Windows (and it worked on all the ones I tried). So, in the next few days I will create an issue with my proposed solution in the php-src repository and see if the PHP developers agree to implement it in PHP.

If they don't agree, we can use your solution (after fixing the bugs). Or if they agree with my solution, maybe we can use your solution in the meantime until my solution is implemented in PHP itself.

**Comment by driesvints** [comment]
Hi all. Wanted to check in if it's still worth keeping this open or not? If there aren't moving parts I feel like it's best that we close this and move on.

**Comment by wouterj** [comment]
The issue has been completely hijacked by supporting Windows. I'm not sure about any of that topic :slightly_smiling_face: 

I would still love to have seen some of the interactivity tools from Prompts as new Questions in the Symfony Console's question helper instead, to help the broader PHP community with these modern features. For what it's worth, we think it's OK to keep the current state as a fallback for Windows, and use the better interaction in terminals that have support.

**Comment by driesvints** [comment]
Hi @wouterj. Sounds good. We'll leave this open a bit longer. @ppastercik let's focus on Windows support in a different issue to keep this one on topic.

**Comment by crazywhalecc** [comment]
@ppastercik @andyduke 

Hi, and sorry for mentioning this out of the blue. I know nothing about windows cmd environment, and I've been looking forward to a laravel prompts that supports windows for a long time.

Here's my perspective:

- It would be better if @andyduke's console-keyboard functions can be written as pecl extension. (pecl extension can be statically linked into php.exe, and compiling and adding it will be much easier)
- Laravel prompts may have a extension detector and first check whether the extension exists, then throw an exception if not supported.
- It seems that this RFC has not been noticed, but I don't think it should be a barrior to Windows CMD compatibility.

**Comment by driesvints** [comment]
@crazywhalecc heya, as mentioned above. Let's please focus this on the topic at hand and keep everything Windows related in a separate issue. Feel free to open one if needed.

**Comment by wouterj** [comment]
Let's close this issue. It's apparent that nobody at Laravel's side is interested in contributing part of this back to Symfony Console. So the most logical step is to wait for someone in the Symfony community really wanting this feature and contributing it to Symfony themselves.

Thanks for the discussion!

**Comment by driesvints** [comment]
> It's apparent that nobody at Laravel's side is interested in contributing part of this back to Symfony Console.

Hey @wouterj. That's a bit harsh as that's definitely not true. We'd definitely want to open up the prompts package to the larger PHP community. We just struggle to find time to look into it more deeply as we have a lot of other things going on at Laravel.

In fact, as soon as I find the time I'm going to look into getting rid of the `illuminate/collection` dependency so the package is even less dependant on Laravel. I really want to get that in before we tag a v1.0

Of course, this package is open-source and we'd very much welcome PR's that help open up this package further to other frameworks as long as we also make sure it doesn't breaks existing (Laravel) apps.

**Comment by wouterj** [comment]
Hi @driesvints. Sorry if my message came across harsh. There was no plan or update in this issue for almost a year, so I expected there was no intention to act here. I also realize that it's much more likely that someone from the non-Laravel users of the Console component will be motivated to work on this because they want slick CLI interfaces as well.

For me, that's what open source is about: someone that wants something, should put in the work. So I didn't want to leave this open on the Laravel side (were I don't expect someone to be motivated about this, because this works just fine already for Laravel users).

Anyway, cool to hear you have plans to one day decouple this package more from Laravel!

**Comment by driesvints** [comment]
Thanks @wouterj. I appreciate the feedback 😄
