### ISSUE TITLE
can it add support for laravel 9 and 8 ?

### ISSUE THREAD

**Issue by jhonoryza** [laravel/prompts#18]
i see in composer.json require "illuminate/collections": "^10.0" which is support only for laravel 10, i have an old laravel apps using version 8 and 9, i want using this prompts package 😄

**Comment by jessarcher** [comment]
I'm not opposed to supporting older versions of `illuminate/collections` for use in your own console commands, but we don't plan to include Prompts in older versions of Laravel's built-in commands.

I don't want to change the dependency requirements until the corresponding framework PR at https://github.com/laravel/framework/pull/46772/files is merged because the circular dependency has already caused some issues. Feel free to submit a PR here once that is merged so Taylor can consider it.
