### ISSUE TITLE
Track typed value on Multiselect and Select

### ISSUE THREAD

**Issue by utsavsomaiya** [laravel/prompts#75]
Let's take one example:

![image](https://github.com/laravel/prompts/assets/96036522/73e06b9f-3501-4da2-8272-d53fb1992c44)

Now I will down to the next page which is already PR pending. But when I type rather than the [`default` is `null`](https://github.com/laravel/prompts/blob/main/src/SelectPrompt.php#L76) at that time we will introduce search!!.

**Comment by utsavsomaiya** [comment]
https://github.com/laravel/prompts/assets/96036522/98ffcb85-a1e6-457d-a2a2-34079e5b18d7

Here is the real-world use case!! I pressed version 5 then it will highlight 5.

**Comment by utsavsomaiya** [comment]
When it's too large select the box rather than going down. It will become fast!!

**Comment by utsavsomaiya** [comment]
Something like this:

https://github.com/laravel/prompts/assets/96036522/71baacb2-ef08-4df6-8273-3bb8de5e948b

**Comment by jessarcher** [comment]
Hey @utsavsomaiya,

Thanks for the suggestion. This is something I've wanted to do from the beginning to make Prompts even more like web-based form inputs. I even thought that once you started typing letters, it could show a search field somewhere and then filter the list instead of just jumping to the first matching item, which would improve what the standard web-based form inputs do. I'm not sure where I would display the text input though as any increase in the prompt height can be jarring if the prompt is at the bottom of the terminal.

I'm also a little torn on how much we need it now that we have the `search` prompt and hopefully the `multisearch` prompt (#58), which are better for large lists.

This isn't a big priority for me at the moment, so it might be a while before I can look into it. I'm open to PRs as long as the UX feels right.

**Comment by utsavsomaiya** [comment]
Okay... no worries @jessarcher .

I closed this issue.

**Comment by utsavsomaiya** [comment]
@jessarcher Can we add password reveal functionality on password prompt?

**Comment by jessarcher** [comment]
@utsavsomaiya how would you propose it's toggled on and off?

**Comment by utsavsomaiya** [comment]
Get the key from the users or static any key. And when it's press it will be on ... next time it press it will be off.

**Comment by jessarcher** [comment]
What key do you think would be a good default? And how would we let the user know the feature exists and how to toggle it?

I was thinking maybe an icon/button on the right (where the arrow currently appears on the `suggest` prompt), and you could press `Tab` to highlight it and `Space` to toggle it. Not sure, though.

**Comment by utsavsomaiya** [comment]
Okay @jessarcher 

I will make a PR. After you will suggest me. So its confirmed first with you. That's why we both understand the flow.

Thanks. ☺

**Comment by jessarcher** [comment]
I can't make any promises about it getting accepted - it's ultimately up to Taylor. But if you really want the feature then it's worth having a go :slightly_smiling_face:

**Comment by utsavsomaiya** [comment]
> I can't make any promises about it getting accepted - it's ultimately up to Taylor. But if you really want the feature then it's worth having a go :slightly_smiling_face: 

![image](https://github.com/laravel/prompts/assets/96036522/b92fb0fd-eea5-416f-9f11-8a444486e865)

Okay
