### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [laravel/prompts#8]
### Laravel Prompts Version

0.1.0

### Laravel Version

10.10

### PHP Version

8.1

### Operating System & Version

Windows 10 Enterprise

### Terminal Application

bash Terminal

### Description

I used `text` and `search` methods in my command class then when I run the command this error is raised **The system cannot find the path specified**, after that when I tried to open `TextPrompt` (for example) I found that the class not exists.

### Steps To Reproduce

When I use any method of that package this error message **The system cannot find the path specified** is raised.

**Comment by jessarcher** [comment]
Hey @mahmoudmohamedramadan, are you running Prompts in WSL or just native Windows?

Unfortunately, it's not currently possible to use Prompts in native Windows due to environmental limitations (see https://github.com/laravel/docs/pull/8924#issuecomment-1654762739 for more information)

Once we've merged https://github.com/laravel/framework/pull/46772 into Laravel, the prompts should automatically fall back to Symfony prompts in unsupported environments.

**Comment by jessarcher** [comment]
I've created PR #20 to display a more helpful error message when running in an unsupported environment without a fallback.

**Comment by mahmoudmohamedramadan** [comment]
Awesome, thank you!
