### ISSUE TITLE
character "❯" cant show on windows

### ISSUE THREAD

**Issue by SocolaDaiCa** [laravel/prompts#95]
### Laravel Prompts Version

0.1.11

### Laravel Version

10.26.2

### PHP Version

8.2

### Operating System & Version

Windows

### Terminal Application

cmder

### Description

![image](https://github.com/laravel/prompts/assets/18243451/32fc1d84-91ab-4594-b12e-3240d63580b1)
character "❯" cant show on windows, it show square with question mask

### Steps To Reproduce

run function text:

```php
dump(
    text('What is your name?', 'placeholder', 'SocolaDaiCa', true, function ($value) {
            if ($value === 'bad') {
                return 'a';
            }

            return '';
        }, 'hint'
    )
);
```

**Comment by jessarcher** [comment]
Hey @SocolaDaiCa,

This character doesn't come from Prompts. On Windows, we have to fall back to using Symfony for the prompts due to platform limitations. The character you're (not) seeing comes from `laravel/framework` at https://github.com/laravel/framework/blob/cddb4f3bb5231f44f18fce304dbf190ad8348ddc/src/Illuminate/Console/QuestionHelper.php#L67 (it may potentially exist in other places too)

It's a limitation of the font you're using in your terminal, rather than anything specifically to do with Windows. If you're using a common font or the default font in a common terminal, it might be worth trying a PR to `laravel/framework` to change that character to something more widely supported.
